name: kumbhraj_mandi
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  firebase_database: ^10.2.6
    





  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1






  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
 uses-material-design: true

  
 assets:
    - assets/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
