// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbjtDKrIK-3l5chl9lIrRszYAwG02xrJQ',
    appId: '1:675786252519:web:47a3a46f5191f153dac242',
    messagingSenderId: '675786252519',
    projectId: 'kumbhraj-mandi-minor-project',
    authDomain: 'kumbhraj-mandi-minor-project.firebaseapp.com',
    storageBucket: 'kumbhraj-mandi-minor-project.appspot.com',
    measurementId: 'G-LD0G82HXF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-TDFKKc30zoogd_ZH2J04aLhS2xdgUJg',
    appId: '1:675786252519:android:5a73855add9097cbdac242',
    messagingSenderId: '675786252519',
    projectId: 'kumbhraj-mandi-minor-project',
    storageBucket: 'kumbhraj-mandi-minor-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHFKrFJxFGAWh4YHTog057DwI0MVExFEI',
    appId: '1:675786252519:ios:3f1503d9852e40a9dac242',
    messagingSenderId: '675786252519',
    projectId: 'kumbhraj-mandi-minor-project',
    storageBucket: 'kumbhraj-mandi-minor-project.appspot.com',
    iosBundleId: 'com.example.kumbhrajMandi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHFKrFJxFGAWh4YHTog057DwI0MVExFEI',
    appId: '1:675786252519:ios:718fe0f8943033d9dac242',
    messagingSenderId: '675786252519',
    projectId: 'kumbhraj-mandi-minor-project',
    storageBucket: 'kumbhraj-mandi-minor-project.appspot.com',
    iosBundleId: 'com.example.kumbhrajMandi.RunnerTests',
  );
}
